# Generated by Django 4.2.4 on 2023-09-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
